---
title: "Boundary layer new particle formation over East Antarctic sea ice–possible Hg-driven nucleation?"
type: "article"
author: "Humphries, R.S., Schofield, R., Keywood, M.D., Ward, J., Pierce, J.R., Gionfriddo, C.M., Tate, M.T., Krabbenhoft, D.P., Galbally, I.E., Molloy, S.B. and Klekociuk, A.R."
year: "2015"
publication: "Atmospheric Chemistry and Physics"
# preprint: "https://psyarxiv.com/gqhjr"
doi: "https://doi.org/10.5194/acp-15-13339-2015"
# materials: "https://osf.io/qu3f6/"
toc: false
categories:
  - oceanography
  - chlorophyll
  - antarctica
  - article
---

## Citation (Harvard)

> Humphries, R.S., Schofield, R., Keywood, M.D., Ward, J., Pierce, J.R., Gionfriddo, C.M., Tate, M.T., Krabbenhoft, D.P., Galbally, I.E., Molloy, S.B. and Klekociuk, A.R., 2015. Boundary layer new particle formation over East Antarctic sea ice–possible Hg-driven nucleation?. Atmospheric Chemistry and Physics, 15(23), pp.13339-13364.

## Abstract

Aerosol observations above the Southern Ocean and Antarctic sea ice are scarce. Measurements of aerosols and atmospheric composition were made in East Antarctic pack ice on board the Australian icebreaker Aurora Australis during the spring of 2012. One particle formation event was observed during the 32 days of observations. This event occurred on the only day to exhibit extended periods of global irradiance in excess of 600 W m−2. Within the single air mass influencing the measurements, number concentrations of particles larger than 3 nm (CN3) reached almost 7700 cm−3 within a few hours of clouds clearing, and grew at rates of 5.6 nm h−1. Formation rates of 3 nm particles were in the range of those measured at other Antarctic locations at 0.2–1.1 ± 0.1 cm−3 s−1. Our investigations into the nucleation chemistry found that there were insufficient precursor concentrations for known halogen or organic chemistry to explain the nucleation event. Modelling studies utilising known sulfuric acid nucleation schemes could not simultaneously reproduce both particle formation or growth rates. Surprising correlations with total gaseous mercury (TGM) were found that, together with other data, suggest a mercury-driven photochemical nucleation mechanism may be responsible for aerosol nucleation. Given the very low vapour pressures of the mercury species involved, this nucleation chemistry is likely only possible where pre-existing aerosol concentrations are low and both TGM concentrations and solar radiation levels are relatively high (∼ 1.5 ng m−3 and ≥ 600 W m−2, respectively), such as those observed in the Antarctic sea ice boundary layer in this study or in the global free troposphere, particularly in the Northern Hemisphere.