---
title: "Zooplankton abundance and biomass size spectra in the East Antarctic sea-ice zone during the winter–spring transition"
type: "article"
author: "Wallis, J.R., Swadling, K.M., Everett, J.D., Suthers, I.M., Jones, H.J., Buchanan, P.J., Crawford, C.M., James, L.C., Johnson, R., Meiners, K.M. and Virtue, P."
year: "2016"
publication: "Deep Sea Research Part II: Topical Studies in Oceanography"
# preprint: "https://psyarxiv.com/gqhjr"
doi: "https://doi.org/10.1016/j.dsr2.2015.10.002"
# materials: "https://osf.io/qu3f6/"
toc: false
categories:
  - oceanography
  - zooplankton
  - chlorophyll
  - antarctica
  - article
---

## Citation (Harvard)

> Wallis, J.R., Swadling, K.M., Everett, J.D., Suthers, I.M., Jones, H.J., Buchanan, P.J., Crawford, C.M., James, L.C., Johnson, R., Meiners, K.M. and Virtue, P., 2016. Zooplankton abundance and biomass size spectra in the East Antarctic sea-ice zone during the winter–spring transition. Deep Sea Research Part II: Topical Studies in Oceanography, 131, pp.170-181.

## Abstract

Sea ice is an influential feature in Southern Ocean-Antarctic marine environments creating a 2-phase vertical ecosystem. The lack of information on how this system influences community structure during the winter-spring transition, however, is largely lacking. Zooplankton form the link that bridges these environments, with the meiofaunal and algal communities within sea ice directly influencing the epipelagic zooplankton community at the ice-water interface. A combination of methods including sea-ice coring, umbrella net sampling and Laser Optical Plankton Counter were used to describe the vertical structure of zooplankton and meiofaunal communities. The distribution of meiofauna and chlorophyll a both played important roles in structuring the zooplankton community within this dynamic region. Many dominant taxa, including Calanus propinquus and Oithona similis, directly responded to the high availability of algae present within the bottom strata of sea ice. The sea-ice associated species Stephos longipes represented a strong link between this 2-phase ecosystem. Observations of the vertical distribution of biomass obtained from the LOPC suggests that the responses of these species to the sea ice directly influences the vertical structure of zooplankton during the winter-spring transition.